import { Navbar } from "@/components/navbar"
import { Footer } from "@/components/footer"
import { Palette, Image, BadgeCheck } from "lucide-react"

const brandCards = [
  {
    title: "Logo + Marks",
    detail: "Primary mark, monochrome, and favicon exports.",
    icon: Image,
  },
  {
    title: "Color System",
    detail: "Primary, accent, and neutral palette applied to artifacts.",
    icon: Palette,
  },
  {
    title: "Verification Badge",
    detail: "Tier badge and provenance stamp on outputs.",
    icon: BadgeCheck,
  },
]

export default function BrandSettingsPage() {
  return (
    <main id="main-content">
      <Navbar />
      <div className="pt-28 pb-20 md:pt-36 md:pb-28">
        <div className="mx-auto w-full max-w-[1200px] px-6">
          <header className="mb-8">
            <p className="text-xs uppercase tracking-wider text-muted-foreground">Settings - Brand</p>
            <h1 className="mt-3 text-3xl md:text-5xl font-serif text-foreground">Brand controls</h1>
            <p className="mt-3 text-sm text-muted-foreground max-w-2xl">
              Brand settings govern every report, deck, and embedded widget generated by Entrestate.
            </p>
          </header>

          <section className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {brandCards.map((card) => (
              <div key={card.title} className="rounded-2xl border border-border/70 bg-card/70 p-6">
                <card.icon className="h-5 w-5 text-accent" />
                <h2 className="mt-4 text-lg font-semibold text-foreground">{card.title}</h2>
                <p className="mt-2 text-sm text-muted-foreground">{card.detail}</p>
              </div>
            ))}
          </section>
        </div>
      </div>
      <Footer />
    </main>
  )
}
